### ISSUE TITLE
SpriteAnimation.animate() : first frame played twice

### ISSUE THREAD

**Issue by jmaupoux** [craftyjs/Crafty#336]
Hi,
The first frame on .animate() id played twice :
Here is my code :

Crafty.e("").animate("walk_down", [[0,1], [0,2], [0,0]]);
...
Crafty(id).animate("walk_down", 50, 0);

To fix it, i changed currentSlideNumber to 1 on animate()::var this._frame initialization. 
Not sure thats the proper way to fix but the following code is triggered after (total frames)/(number frames) does not change the frame played on first frame because (++ is executed after [ ] so still return 0 after first if match) :
var pos = data.currentReel[data.currentSlideNumber++];

**Comment by ahilles107** [comment]
What version? I think that this was fixed before.

**Comment by jmaupoux** [comment]
i m on v0.4.9 but tried current master SpriteAnimation version and still the same behavior

**Comment by thehack** [comment]
me too.

**Comment by mpetrovic** [comment]
That'll all end up rewritten for the Layers update anyway. I could try backporting it for the current version.

**Comment by jmaupoux** [comment]
I patched it it's ok for me you can focus on next implementation if soon released

**Comment by starwed** [comment]
I'm pretty sure this is fixed by  #426, so closing.
